[package]
name = "bazuka"
version = "0.1.0"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"], optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
futures = { version = "0.3", optional = true }
leveldb = { version = "0.8.6", optional = true }
structopt = { version = "0.3", default-features = false, optional = true }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_qs = "0.8"
home = "0.5.3"
db-key = "0.0.5"
ff = { version = "0.11", features = ["derive"] }
sha3 = "0.10.0"
bincode = "1.3.3"
thiserror = "1.0"
num-bigint = "0.4"
num-integer = "0.1"
typenum = "1.15.0"
generic-array = "0.14.5"
rand = "0.8.5"
rand_core = "0.6"
schnorrkel = { version = "0.9.1", features = [
    "preaudit_deprecated",
    "u64_backend",
    "getrandom",
    "rand",
    "std"
], default-features = false }
merlin = "2.0.0"
hex = "0.4.3"
hmac = "0.11.0"
pbkdf2 = "0.8.0"
sha2 = "0.9"
zeroize = "1.0"
tiny-bip39 = "0.8.0"

[features]
node = ["tokio", "hyper", "leveldb", "futures", "structopt"]
