[package]
name = "bazuka"
version = "0.1.0"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>"]
edition = "2021"

[workspace]
members = [".", "bin"]

[dependencies]
tokio = { version = "1", features = ["full"], optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
leveldb = { version = "0.8.6", optional = true }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
home = "0.5.3"
db-key = "0.0.5"
ff = { version = "0.11", features = ["derive"] }
sha3 = "0.10.0"
bincode = "1.3.3"
rand = "0.8.5"
thiserror = "1.0"
num-rational = "0.2"
num-traits = "0.2"
num-bigint = "0.4"
num-integer = "0.1"
schnorrkel = "0.10.2"
async-trait = "0.1.52"
secrecy = "0.8.0"
futures-timer = "3.0.2"
log = "0.4.14"
merlin = "3.0.0"
rocksdb = "0.18.0"
anyhow = "1.0"
byteorder = "1.0"
lru = "0.7"

[features]
node = ["tokio", "hyper", "leveldb"]
